import type { BrowserAdapter } from '../browser/adapter.js';
import {
  runAgentLoop,
  type LoopResult,
} from '../loop/agentLoop.js';
import type { CallModel } from '../loop/messages.js';
import {
  DEFAULT_MODEL,
  makeCallModel,
  type ProgressEvent,
} from '../model/callModel.js';
import {
  finalizeManifest,
  initManifest,
} from '../run/artifacts.js';
import { generateRunId } from '../run/runId.js';
import { createRunDir } from '../run/runDir.js';
import {
  createRunTracing,
  type RunTracing,
} from '../tracing/runTracing.js';
import {
  actionTools,
  evidenceTools,
  fileTools,
  observationTools,
} from '../tools/index.js';
import {
  createRegistry,
  toApiToolDefs,
} from '../tools/registry.js';
import { SYSTEM_PROMPT } from './systemPrompt.js';

const DEFAULT_RUNS_BASE_DIR = 'runs';
const DEFAULT_MAX_OUTPUT_TOKENS = 8_192;
const DEFAULT_MAX_TURNS = 24;
const DEFAULT_MAX_TOKENS = 250_000;

/** Configuration for one complete evidence-collection run. */
export interface RunTaskConfig {
  /** A live session browser with no active task tab. The caller owns and
   * eventually closes the session; runTask owns only the fresh tab it opens. */
  browser: BrowserAdapter;
  /** Directory that holds run directories; defaults to `runs`. */
  runsBaseDir?: string;
  /** Optional HTTP(S) page to load before the first model turn. */
  startUrl?: string;
  /** Model id; the production model client's default when omitted. */
  model?: string;
  /** Maximum tokens generated by each production model call; defaults to 8192. */
  maxOutputTokens?: number;
  /** Maximum model turns in the loop; defaults to 24. */
  maxTurns?: number;
  /** Cumulative loop token budget; defaults to 250000. */
  maxTokens?: number;
  /** Optional callback for production model streaming progress. */
  onProgress?: (event: ProgressEvent) => void;
  /** Optional model implementation for tests or alternate clients. When
   * omitted, runTask creates the production streaming Anthropic client. */
  callModel?: CallModel;
  /** Optional run-scoped tracing implementation. When omitted, tracing is
   * configured from LANGFUSE_* environment variables or becomes a no-op. */
  tracing?: RunTracing;
}

/** The finished run directory together with the loop's terminal outcome. */
export type RunTaskResult = { runDir: string } & LoopResult;

/**
 * Run one task through the production evidence-collection stack.
 *
 * @param taskText - the user's task, recorded verbatim in the manifest and
 *   sent as the first conversation message
 * @param config - a live browser session with no active task tab plus
 *   optional run location, starting page, model settings, and loop guards;
 *   `callModel` may replace the production client at this dependency seam
 * @returns the absolute run directory and terminal loop outcome; before the
 *   promise resolves, the transcript and metrics are complete, the manifest
 *   is finalized, and this run's tab is closed while the browser stays open
 */
export async function runTask(
  taskText: string,
  config: RunTaskConfig,
): Promise<RunTaskResult> {
  const maxOutputTokens = config.maxOutputTokens ?? DEFAULT_MAX_OUTPUT_TOKENS;
  if (!Number.isInteger(maxOutputTokens) || maxOutputTokens < 1) {
    throw new Error(
      `maxOutputTokens must be a positive integer, got ${maxOutputTokens}`,
    );
  }

  const registry = createRegistry([
    ...fileTools,
    ...observationTools,
    ...actionTools,
    ...evidenceTools,
  ]);
  const baseCallModel = config.callModel ?? makeCallModel({
    model: config.model,
    system: SYSTEM_PROMPT,
    apiToolDefs: toApiToolDefs(registry),
    maxOutputTokens,
    onProgress: config.onProgress,
  });

  const runDir = createRunDir(
    config.runsBaseDir ?? DEFAULT_RUNS_BASE_DIR,
    // The task text names the run dir (slugified), so listings read like a
    // history of what was asked rather than a wall of timestamps.
    generateRunId(taskText),
  );
  initManifest(runDir, taskText);

  const tracing = config.tracing ?? createRunTracing();
  const callModel = tracing.wrapCallModel(
    baseCallModel,
    config.model ?? DEFAULT_MODEL,
  );
  const tracedRegistry = tracing.wrapRegistry(registry);

  let tabOpened = false;
  try {
    const result = await tracing.traceRun(taskText, async () => {
      await config.browser.newTab();
      tabOpened = true;

      if (config.startUrl !== undefined) {
        await config.browser.goto(config.startUrl);
      }

      return runAgentLoop(
        taskText,
        { callModel, registry: tracedRegistry, runDir, browser: config.browser },
        {
          maxTurns: config.maxTurns ?? DEFAULT_MAX_TURNS,
          maxTokens: config.maxTokens ?? DEFAULT_MAX_TOKENS,
        },
      );
    });
    return { runDir, ...result };
  } finally {
    try {
      if (tabOpened) {
        await config.browser.closeTab();
      }
    } finally {
      try {
        finalizeManifest(runDir);
      } finally {
        await tracing.close();
      }
    }
  }
}
